### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by nedtwigg** [diffplug/blowdryer#13]
To add GitLab support, you'll need to add a method to `BlowdryerSetup` similar to the `github` method:

https://github.com/diffplug/blowdryer/blob/d116192b0692e80828cfe307382629748c22a560/src/main/java/com/diffplug/blowdryer/BlowdryerSetup.java#L56-L62

**Comment by vgropp** [comment]
yes, i already found that, I will open the PR later today.

**Comment by nedtwigg** [comment]
- [ ] TODO @nedtwigg change the GitLab test repos to be under diffplug incase vgropp brings down test repo someday

**Comment by nedtwigg** [comment]
Implemented in `1.1.0` thanks to @vgropp.
