### ISSUE TITLE
Can't import in settings.gradle.kts

### ISSUE THREAD

**Issue by lyharrietbui** [diffplug/blowdryer#29]
I have a kotlin project and I am not able to do 
```
import com.diffplug.blowdryer.BlowdryerSetup
import com.diffplug.blowdryer.BlowdryerSetup.GitAnchorType
```
after applying the plugin in `settings.gradle.kts`. Gradle can't resolve the plugin. I also added maven url and classpath in the buildscript of the `build.gradle.kts` file in the root folder of the project

**Comment by nedtwigg** [comment]
> I also added maven url and classpath in the buildscript of the build.gradle.kts

You have to apply blowdryer inside of `settings.gradle`, not just the root `build.gradle`, so you'll have to specify the maven URL inside `settings.gradle` too (I assume you've got a corporate proxy, which is why you can just use the portal?)
